# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eliteOCRGUI.ui'
#
# Created: Mon Nov 10 12:59:53 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_eliteOCR(object):
    def setupUi(self, eliteOCR):
        eliteOCR.setObjectName(_fromUtf8("eliteOCR"))
        eliteOCR.resize(1096, 674)
        self.centralwidget = QtGui.QWidget(eliteOCR)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.path_to_image = QtGui.QLineEdit(self.centralwidget)
        self.path_to_image.setObjectName(_fromUtf8("path_to_image"))
        self.horizontalLayout.addWidget(self.path_to_image)
        self.image_button = QtGui.QPushButton(self.centralwidget)
        self.image_button.setObjectName(_fromUtf8("image_button"))
        self.horizontalLayout.addWidget(self.image_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.station_name_img = QtGui.QGraphicsView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.station_name_img.sizePolicy().hasHeightForWidth())
        self.station_name_img.setSizePolicy(sizePolicy)
        self.station_name_img.setMaximumSize(QtCore.QSize(16777215, 20))
        self.station_name_img.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.station_name_img.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.station_name_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.station_name_img.setObjectName(_fromUtf8("station_name_img"))
        self.horizontalLayout_5.addWidget(self.station_name_img)
        self.station_name = QtGui.QLineEdit(self.centralwidget)
        self.station_name.setObjectName(_fromUtf8("station_name"))
        self.horizontalLayout_5.addWidget(self.station_name)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.demand_img = QtGui.QGraphicsView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.demand_img.sizePolicy().hasHeightForWidth())
        self.demand_img.setSizePolicy(sizePolicy)
        self.demand_img.setMaximumSize(QtCore.QSize(16777215, 20))
        self.demand_img.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.demand_img.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.demand_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.demand_img.setRenderHints(QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.demand_img.setObjectName(_fromUtf8("demand_img"))
        self.gridLayout.addWidget(self.demand_img, 1, 3, 1, 1)
        self.supply_num = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(14)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.supply_num.sizePolicy().hasHeightForWidth())
        self.supply_num.setSizePolicy(sizePolicy)
        self.supply_num.setObjectName(_fromUtf8("supply_num"))
        self.gridLayout.addWidget(self.supply_num, 3, 5, 1, 1)
        self.supply_img = QtGui.QGraphicsView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.supply_img.sizePolicy().hasHeightForWidth())
        self.supply_img.setSizePolicy(sizePolicy)
        self.supply_img.setMaximumSize(QtCore.QSize(16777215, 20))
        self.supply_img.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.supply_img.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.supply_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.supply_img.setRenderHints(QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.supply_img.setObjectName(_fromUtf8("supply_img"))
        self.gridLayout.addWidget(self.supply_img, 1, 5, 1, 1)
        self.supply_text_img = QtGui.QGraphicsView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.supply_text_img.sizePolicy().hasHeightForWidth())
        self.supply_text_img.setSizePolicy(sizePolicy)
        self.supply_text_img.setMaximumSize(QtCore.QSize(16777215, 20))
        self.supply_text_img.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.supply_text_img.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.supply_text_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.supply_text_img.setRenderHints(QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.supply_text_img.setObjectName(_fromUtf8("supply_text_img"))
        self.gridLayout.addWidget(self.supply_text_img, 1, 6, 1, 1)
        self.demand_text_img = QtGui.QGraphicsView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.demand_text_img.sizePolicy().hasHeightForWidth())
        self.demand_text_img.setSizePolicy(sizePolicy)
        self.demand_text_img.setMaximumSize(QtCore.QSize(16777215, 20))
        self.demand_text_img.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.demand_text_img.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.demand_text_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.demand_text_img.setRenderHints(QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.demand_text_img.setObjectName(_fromUtf8("demand_text_img"))
        self.gridLayout.addWidget(self.demand_text_img, 1, 4, 1, 1)
        self.demand_num = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(14)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.demand_num.sizePolicy().hasHeightForWidth())
        self.demand_num.setSizePolicy(sizePolicy)
        self.demand_num.setObjectName(_fromUtf8("demand_num"))
        self.gridLayout.addWidget(self.demand_num, 3, 3, 1, 1)
        self.name = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(43)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name.sizePolicy().hasHeightForWidth())
        self.name.setSizePolicy(sizePolicy)
        self.name.setObjectName(_fromUtf8("name"))
        self.gridLayout.addWidget(self.name, 3, 0, 1, 1)
        self.sell = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sell.sizePolicy().hasHeightForWidth())
        self.sell.setSizePolicy(sizePolicy)
        self.sell.setObjectName(_fromUtf8("sell"))
        self.gridLayout.addWidget(self.sell, 3, 1, 1, 1)
        self.buy = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buy.sizePolicy().hasHeightForWidth())
        self.buy.setSizePolicy(sizePolicy)
        self.buy.setObjectName(_fromUtf8("buy"))
        self.gridLayout.addWidget(self.buy, 3, 2, 1, 1)
        self.demand = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.demand.sizePolicy().hasHeightForWidth())
        self.demand.setSizePolicy(sizePolicy)
        self.demand.setObjectName(_fromUtf8("demand"))
        self.gridLayout.addWidget(self.demand, 3, 4, 1, 1)
        self.buy_img = QtGui.QGraphicsView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buy_img.sizePolicy().hasHeightForWidth())
        self.buy_img.setSizePolicy(sizePolicy)
        self.buy_img.setMaximumSize(QtCore.QSize(16777215, 20))
        self.buy_img.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.buy_img.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.buy_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.buy_img.setRenderHints(QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.buy_img.setObjectName(_fromUtf8("buy_img"))
        self.gridLayout.addWidget(self.buy_img, 1, 2, 1, 1)
        self.name_img = QtGui.QGraphicsView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_img.sizePolicy().hasHeightForWidth())
        self.name_img.setSizePolicy(sizePolicy)
        self.name_img.setMinimumSize(QtCore.QSize(0, 0))
        self.name_img.setMaximumSize(QtCore.QSize(16777215, 20))
        self.name_img.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.name_img.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.name_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.name_img.setRenderHints(QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.name_img.setObjectName(_fromUtf8("name_img"))
        self.gridLayout.addWidget(self.name_img, 1, 0, 1, 1)
        self.sell_img = QtGui.QGraphicsView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sell_img.sizePolicy().hasHeightForWidth())
        self.sell_img.setSizePolicy(sizePolicy)
        self.sell_img.setMaximumSize(QtCore.QSize(16777215, 20))
        self.sell_img.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sell_img.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sell_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sell_img.setRenderHints(QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.sell_img.setObjectName(_fromUtf8("sell_img"))
        self.gridLayout.addWidget(self.sell_img, 1, 1, 1, 1)
        self.supply = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.supply.sizePolicy().hasHeightForWidth())
        self.supply.setSizePolicy(sizePolicy)
        self.supply.setObjectName(_fromUtf8("supply"))
        self.gridLayout.addWidget(self.supply, 3, 6, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.skip_button = QtGui.QPushButton(self.centralwidget)
        self.skip_button.setObjectName(_fromUtf8("skip_button"))
        self.verticalLayout_3.addWidget(self.skip_button)
        self.save_button = QtGui.QPushButton(self.centralwidget)
        self.save_button.setObjectName(_fromUtf8("save_button"))
        self.verticalLayout_3.addWidget(self.save_button)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.result_table = QtGui.QTableWidget(self.centralwidget)
        self.result_table.setObjectName(_fromUtf8("result_table"))
        self.result_table.setColumnCount(0)
        self.result_table.setRowCount(0)
        self.horizontalLayout_4.addWidget(self.result_table)
        self.preview = QtGui.QGraphicsView(self.centralwidget)
        self.preview.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.preview.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.preview.setObjectName(_fromUtf8("preview"))
        self.horizontalLayout_4.addWidget(self.preview)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.export_button = QtGui.QPushButton(self.centralwidget)
        self.export_button.setObjectName(_fromUtf8("export_button"))
        self.horizontalLayout_2.addWidget(self.export_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        eliteOCR.setCentralWidget(self.centralwidget)

        self.retranslateUi(eliteOCR)
        QtCore.QMetaObject.connectSlotsByName(eliteOCR)

    def retranslateUi(self, eliteOCR):
        eliteOCR.setWindowTitle(_translate("eliteOCR", "EliteOCR", None))
        self.image_button.setText(_translate("eliteOCR", "Chose Image", None))
        self.label_5.setText(_translate("eliteOCR", "Station", None))
        self.label.setText(_translate("eliteOCR", "commodity", None))
        self.label_2.setText(_translate("eliteOCR", "sell", None))
        self.label_3.setText(_translate("eliteOCR", "buy", None))
        self.label_4.setText(_translate("eliteOCR", "demand", None))
        self.label_6.setText(_translate("eliteOCR", "supply", None))
        self.skip_button.setText(_translate("eliteOCR", "Skip", None))
        self.save_button.setText(_translate("eliteOCR", "Save and Next", None))
        self.export_button.setText(_translate("eliteOCR", "Export", None))

