# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'learningUI.ui'
#
# Created: Mon Apr 27 13:36:34 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName(_fromUtf8("Wizard"))
        Wizard.resize(788, 483)
        Wizard.setWizardStyle(QtGui.QWizard.ModernStyle)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.wizardPage1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_2 = QtGui.QLabel(self.wizardPage1)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.wizardPage1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.base_data_label = QtGui.QLabel(self.wizardPage1)
        self.base_data_label.setWordWrap(True)
        self.base_data_label.setObjectName(_fromUtf8("base_data_label"))
        self.horizontalLayout_5.addWidget(self.base_data_label)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 100)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.wizardPage1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.user_data_label = QtGui.QLabel(self.wizardPage1)
        self.user_data_label.setWordWrap(True)
        self.user_data_label.setObjectName(_fromUtf8("user_data_label"))
        self.horizontalLayout_6.addWidget(self.user_data_label)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 100)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.delete_images_button = QtGui.QPushButton(self.wizardPage1)
        self.delete_images_button.setEnabled(False)
        self.delete_images_button.setObjectName(_fromUtf8("delete_images_button"))
        self.verticalLayout_4.addWidget(self.delete_images_button)
        spacerItem2 = QtGui.QSpacerItem(20, 281, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout_4.setStretch(3, 1)
        self.verticalLayout_4.setStretch(4, 1)
        self.verticalLayout_4.setStretch(6, 10)
        Wizard.addPage(self.wizardPage1)
        self.wizardPage2 = CustomQWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.wizardPage2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.wizardPage2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.file_list = QtGui.QListWidget(self.wizardPage2)
        self.file_list.setMaximumSize(QtCore.QSize(16777215, 100))
        self.file_list.setObjectName(_fromUtf8("file_list"))
        self.horizontalLayout.addWidget(self.file_list)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.add_files_button = QtGui.QPushButton(self.wizardPage2)
        self.add_files_button.setObjectName(_fromUtf8("add_files_button"))
        self.verticalLayout.addWidget(self.add_files_button)
        self.remove_file_button = QtGui.QPushButton(self.wizardPage2)
        self.remove_file_button.setObjectName(_fromUtf8("remove_file_button"))
        self.verticalLayout.addWidget(self.remove_file_button)
        self.ocr_button = QtGui.QPushButton(self.wizardPage2)
        self.ocr_button.setObjectName(_fromUtf8("ocr_button"))
        self.verticalLayout.addWidget(self.ocr_button)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_5 = QtGui.QLabel(self.wizardPage2)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.g18 = QtGui.QGraphicsView(self.wizardPage2)
        self.g18.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g18.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g18.setObjectName(_fromUtf8("g18"))
        self.gridLayout.addWidget(self.g18, 2, 7, 1, 1)
        self.g17 = QtGui.QGraphicsView(self.wizardPage2)
        self.g17.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g17.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g17.setObjectName(_fromUtf8("g17"))
        self.gridLayout.addWidget(self.g17, 2, 6, 1, 1)
        self.g11 = QtGui.QGraphicsView(self.wizardPage2)
        self.g11.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g11.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g11.setObjectName(_fromUtf8("g11"))
        self.gridLayout.addWidget(self.g11, 2, 0, 1, 1)
        self.g9 = QtGui.QGraphicsView(self.wizardPage2)
        self.g9.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g9.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g9.setObjectName(_fromUtf8("g9"))
        self.gridLayout.addWidget(self.g9, 0, 8, 1, 1)
        self.g19 = QtGui.QGraphicsView(self.wizardPage2)
        self.g19.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g19.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g19.setObjectName(_fromUtf8("g19"))
        self.gridLayout.addWidget(self.g19, 2, 8, 1, 1)
        self.g10 = QtGui.QGraphicsView(self.wizardPage2)
        self.g10.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g10.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g10.setObjectName(_fromUtf8("g10"))
        self.gridLayout.addWidget(self.g10, 0, 9, 1, 1)
        self.g13 = QtGui.QGraphicsView(self.wizardPage2)
        self.g13.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g13.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g13.setObjectName(_fromUtf8("g13"))
        self.gridLayout.addWidget(self.g13, 2, 2, 1, 1)
        self.g14 = QtGui.QGraphicsView(self.wizardPage2)
        self.g14.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g14.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g14.setObjectName(_fromUtf8("g14"))
        self.gridLayout.addWidget(self.g14, 2, 3, 1, 1)
        self.g15 = QtGui.QGraphicsView(self.wizardPage2)
        self.g15.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g15.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g15.setObjectName(_fromUtf8("g15"))
        self.gridLayout.addWidget(self.g15, 2, 4, 1, 1)
        self.g16 = QtGui.QGraphicsView(self.wizardPage2)
        self.g16.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g16.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g16.setObjectName(_fromUtf8("g16"))
        self.gridLayout.addWidget(self.g16, 2, 5, 1, 1)
        self.g7 = QtGui.QGraphicsView(self.wizardPage2)
        self.g7.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g7.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g7.setObjectName(_fromUtf8("g7"))
        self.gridLayout.addWidget(self.g7, 0, 6, 1, 1)
        self.g12 = QtGui.QGraphicsView(self.wizardPage2)
        self.g12.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g12.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g12.setObjectName(_fromUtf8("g12"))
        self.gridLayout.addWidget(self.g12, 2, 1, 1, 1)
        self.g8 = QtGui.QGraphicsView(self.wizardPage2)
        self.g8.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g8.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g8.setObjectName(_fromUtf8("g8"))
        self.gridLayout.addWidget(self.g8, 0, 7, 1, 1)
        self.g20 = QtGui.QGraphicsView(self.wizardPage2)
        self.g20.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g20.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g20.setObjectName(_fromUtf8("g20"))
        self.gridLayout.addWidget(self.g20, 2, 9, 1, 1)
        self.g6 = QtGui.QGraphicsView(self.wizardPage2)
        self.g6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g6.setObjectName(_fromUtf8("g6"))
        self.gridLayout.addWidget(self.g6, 0, 5, 1, 1)
        self.e3 = QtGui.QLineEdit(self.wizardPage2)
        self.e3.setAlignment(QtCore.Qt.AlignCenter)
        self.e3.setObjectName(_fromUtf8("e3"))
        self.gridLayout.addWidget(self.e3, 1, 2, 1, 1)
        self.e2 = QtGui.QLineEdit(self.wizardPage2)
        self.e2.setAlignment(QtCore.Qt.AlignCenter)
        self.e2.setObjectName(_fromUtf8("e2"))
        self.gridLayout.addWidget(self.e2, 1, 1, 1, 1)
        self.e4 = QtGui.QLineEdit(self.wizardPage2)
        self.e4.setAlignment(QtCore.Qt.AlignCenter)
        self.e4.setObjectName(_fromUtf8("e4"))
        self.gridLayout.addWidget(self.e4, 1, 3, 1, 1)
        self.e5 = QtGui.QLineEdit(self.wizardPage2)
        self.e5.setAlignment(QtCore.Qt.AlignCenter)
        self.e5.setObjectName(_fromUtf8("e5"))
        self.gridLayout.addWidget(self.e5, 1, 4, 1, 1)
        self.g1 = QtGui.QGraphicsView(self.wizardPage2)
        self.g1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g1.setObjectName(_fromUtf8("g1"))
        self.gridLayout.addWidget(self.g1, 0, 0, 1, 1)
        self.g2 = QtGui.QGraphicsView(self.wizardPage2)
        self.g2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g2.setObjectName(_fromUtf8("g2"))
        self.gridLayout.addWidget(self.g2, 0, 1, 1, 1)
        self.e1 = QtGui.QLineEdit(self.wizardPage2)
        self.e1.setAlignment(QtCore.Qt.AlignCenter)
        self.e1.setObjectName(_fromUtf8("e1"))
        self.gridLayout.addWidget(self.e1, 1, 0, 1, 1)
        self.g3 = QtGui.QGraphicsView(self.wizardPage2)
        self.g3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g3.setObjectName(_fromUtf8("g3"))
        self.gridLayout.addWidget(self.g3, 0, 2, 1, 1)
        self.g4 = QtGui.QGraphicsView(self.wizardPage2)
        self.g4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g4.setObjectName(_fromUtf8("g4"))
        self.gridLayout.addWidget(self.g4, 0, 3, 1, 1)
        self.g5 = QtGui.QGraphicsView(self.wizardPage2)
        self.g5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g5.setObjectName(_fromUtf8("g5"))
        self.gridLayout.addWidget(self.g5, 0, 4, 1, 1)
        self.e11 = QtGui.QLineEdit(self.wizardPage2)
        self.e11.setAlignment(QtCore.Qt.AlignCenter)
        self.e11.setObjectName(_fromUtf8("e11"))
        self.gridLayout.addWidget(self.e11, 3, 0, 1, 1)
        self.e12 = QtGui.QLineEdit(self.wizardPage2)
        self.e12.setAlignment(QtCore.Qt.AlignCenter)
        self.e12.setObjectName(_fromUtf8("e12"))
        self.gridLayout.addWidget(self.e12, 3, 1, 1, 1)
        self.e13 = QtGui.QLineEdit(self.wizardPage2)
        self.e13.setAlignment(QtCore.Qt.AlignCenter)
        self.e13.setObjectName(_fromUtf8("e13"))
        self.gridLayout.addWidget(self.e13, 3, 2, 1, 1)
        self.e14 = QtGui.QLineEdit(self.wizardPage2)
        self.e14.setAlignment(QtCore.Qt.AlignCenter)
        self.e14.setObjectName(_fromUtf8("e14"))
        self.gridLayout.addWidget(self.e14, 3, 3, 1, 1)
        self.e15 = QtGui.QLineEdit(self.wizardPage2)
        self.e15.setAlignment(QtCore.Qt.AlignCenter)
        self.e15.setObjectName(_fromUtf8("e15"))
        self.gridLayout.addWidget(self.e15, 3, 4, 1, 1)
        self.e16 = QtGui.QLineEdit(self.wizardPage2)
        self.e16.setAlignment(QtCore.Qt.AlignCenter)
        self.e16.setObjectName(_fromUtf8("e16"))
        self.gridLayout.addWidget(self.e16, 3, 5, 1, 1)
        self.e17 = QtGui.QLineEdit(self.wizardPage2)
        self.e17.setAlignment(QtCore.Qt.AlignCenter)
        self.e17.setObjectName(_fromUtf8("e17"))
        self.gridLayout.addWidget(self.e17, 3, 6, 1, 1)
        self.e18 = QtGui.QLineEdit(self.wizardPage2)
        self.e18.setAlignment(QtCore.Qt.AlignCenter)
        self.e18.setObjectName(_fromUtf8("e18"))
        self.gridLayout.addWidget(self.e18, 3, 7, 1, 1)
        self.e19 = QtGui.QLineEdit(self.wizardPage2)
        self.e19.setAlignment(QtCore.Qt.AlignCenter)
        self.e19.setObjectName(_fromUtf8("e19"))
        self.gridLayout.addWidget(self.e19, 3, 8, 1, 1)
        self.e20 = QtGui.QLineEdit(self.wizardPage2)
        self.e20.setAlignment(QtCore.Qt.AlignCenter)
        self.e20.setObjectName(_fromUtf8("e20"))
        self.gridLayout.addWidget(self.e20, 3, 9, 1, 1)
        self.e6 = QtGui.QLineEdit(self.wizardPage2)
        self.e6.setAlignment(QtCore.Qt.AlignCenter)
        self.e6.setObjectName(_fromUtf8("e6"))
        self.gridLayout.addWidget(self.e6, 1, 5, 1, 1)
        self.e7 = QtGui.QLineEdit(self.wizardPage2)
        self.e7.setAlignment(QtCore.Qt.AlignCenter)
        self.e7.setObjectName(_fromUtf8("e7"))
        self.gridLayout.addWidget(self.e7, 1, 6, 1, 1)
        self.e8 = QtGui.QLineEdit(self.wizardPage2)
        self.e8.setAlignment(QtCore.Qt.AlignCenter)
        self.e8.setObjectName(_fromUtf8("e8"))
        self.gridLayout.addWidget(self.e8, 1, 7, 1, 1)
        self.e9 = QtGui.QLineEdit(self.wizardPage2)
        self.e9.setAlignment(QtCore.Qt.AlignCenter)
        self.e9.setObjectName(_fromUtf8("e9"))
        self.gridLayout.addWidget(self.e9, 1, 8, 1, 1)
        self.e10 = QtGui.QLineEdit(self.wizardPage2)
        self.e10.setAlignment(QtCore.Qt.AlignCenter)
        self.e10.setObjectName(_fromUtf8("e10"))
        self.gridLayout.addWidget(self.e10, 1, 9, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.prev_button = QtGui.QPushButton(self.wizardPage2)
        self.prev_button.setEnabled(False)
        self.prev_button.setObjectName(_fromUtf8("prev_button"))
        self.horizontalLayout_4.addWidget(self.prev_button)
        self.next_button = QtGui.QPushButton(self.wizardPage2)
        self.next_button.setEnabled(False)
        self.next_button.setObjectName(_fromUtf8("next_button"))
        self.horizontalLayout_4.addWidget(self.next_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 100)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(0, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout_3.setStretch(3, 100)
        Wizard.addPage(self.wizardPage2)
        self.wizardPage3 = CustomQWizardPage()
        self.wizardPage3.setObjectName(_fromUtf8("wizardPage3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.wizardPage3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_6 = QtGui.QLabel(self.wizardPage3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.summary_label = QtGui.QLabel(self.wizardPage3)
        self.summary_label.setWordWrap(True)
        self.summary_label.setObjectName(_fromUtf8("summary_label"))
        self.verticalLayout_5.addWidget(self.summary_label)
        self.save_button = QtGui.QPushButton(self.wizardPage3)
        self.save_button.setObjectName(_fromUtf8("save_button"))
        self.verticalLayout_5.addWidget(self.save_button)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem5)
        self.label_7 = QtGui.QLabel(self.wizardPage3)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_5.addWidget(self.label_7)
        self.train_button = QtGui.QPushButton(self.wizardPage3)
        self.train_button.setEnabled(False)
        self.train_button.setObjectName(_fromUtf8("train_button"))
        self.verticalLayout_5.addWidget(self.train_button)
        self.loader = QtGui.QLabel(self.wizardPage3)
        self.loader.setText(_fromUtf8(""))
        self.loader.setAlignment(QtCore.Qt.AlignCenter)
        self.loader.setObjectName(_fromUtf8("loader"))
        self.verticalLayout_5.addWidget(self.loader)
        self.training_summary = QtGui.QLabel(self.wizardPage3)
        self.training_summary.setText(_fromUtf8(""))
        self.training_summary.setWordWrap(True)
        self.training_summary.setObjectName(_fromUtf8("training_summary"))
        self.verticalLayout_5.addWidget(self.training_summary)
        self.details = QtGui.QTextEdit(self.wizardPage3)
        self.details.setObjectName(_fromUtf8("details"))
        self.verticalLayout_5.addWidget(self.details)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 1)
        self.verticalLayout_5.setStretch(2, 1)
        self.verticalLayout_5.setStretch(3, 1)
        self.verticalLayout_5.setStretch(4, 1)
        self.verticalLayout_5.setStretch(5, 1)
        self.verticalLayout_5.setStretch(9, 100)
        Wizard.addPage(self.wizardPage3)

        self.retranslateUi(Wizard)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        Wizard.setWindowTitle(_translate("Wizard", "Wizard", None))
        self.label_2.setText(_translate("Wizard", "This is the learning module. You can improve your OCR accuracy by training OCR with your images. Following learning images are available. You can add more by processing your screenshots in the next step. If you want to restart learning from scratch you can always delete user\'s training images. Base images will not be deleted as they are necessary for proper training.", None))
        self.label_3.setText(_translate("Wizard", "Base learning images:", None))
        self.base_data_label.setText(_translate("Wizard", "-", None))
        self.label_4.setText(_translate("Wizard", "User\'s learning images:", None))
        self.user_data_label.setText(_translate("Wizard", "-", None))
        self.delete_images_button.setText(_translate("Wizard", "Delete user\'s training images", None))
        self.label.setText(_translate("Wizard", "Select Files", None))
        self.add_files_button.setText(_translate("Wizard", "Add Files", None))
        self.remove_file_button.setText(_translate("Wizard", "Remove File", None))
        self.ocr_button.setText(_translate("Wizard", "OCR", None))
        self.label_5.setText(_translate("Wizard", "Dot and comma are the same for learning.\n"
"If two letters are recognized as one use empty text field so it will be ignored while learning.", None))
        self.prev_button.setText(_translate("Wizard", "Previous", None))
        self.next_button.setText(_translate("Wizard", "Next", None))
        self.label_6.setText(_translate("Wizard", "You collected following new images:", None))
        self.summary_label.setText(_translate("Wizard", "-", None))
        self.save_button.setText(_translate("Wizard", "Add those images to user\'s training images", None))
        self.label_7.setText(_translate("Wizard", "Base training data and user\'s training data will be used for OCR training. Click the button above to add just analyzed data to user\'s images. Please note: Learning process can take several minutes to finish! Summary will be show when the training is completed.", None))
        self.train_button.setText(_translate("Wizard", "Perform training", None))

from customqwizardpage import CustomQWizardPage
