# -*- coding: utf-8 -*-
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import re
import pkg_resources

# Patch py2app extension loader to work with gevent
import py2app.util
py2app.util.LOADER = """
def __load():
    imp = __import__("imp")
    os = __import__("os")
    sys = __import__("sys")
    ext = %r
    for path in sys.path:
        if not path.endswith('lib-dynload'):
            continue
        ext_path = os.path.join(path, ext)
        if os.path.exists(ext_path):
            mod = imp.load_dynamic(__name__, ext_path)
            break
    else:
        raise ImportError(repr(ext) + " not found")
__load()
del __load
"""

# Patch py2app recipe enumerator to skip the sip recipe since it's too enthusiastic - we'll list additional Qt modules explicitly
from py2app import recipes
import py2app.build_app
def iterRecipes(module=recipes):
    for name in dir(module):
        if name.startswith('_') or name=='sip']:
            continue
        print name
        check = getattr(getattr(module, name), 'check', None)
        if check is not None:
            yield (name, check)
py2app.build_app.iterRecipes = iterRecipes

VERSION = re.search(r'^appversion\s*=\s*"(.+)"', file('EliteOCR.py').read(), re.MULTILINE).group(1)
APP = ['EliteOCR.py']
DATA_FILES = []
OPTIONS = {'semi_standalone': True,
           'site_packages': False,
           'iconfile': 'EliteOCR.icns',
           'optimize': 2,
           'resources': [pkg_resources.resource_filename('py2app', 'recipes/qt.conf'),	# http://doc.qt.io/qt-4.8/qt-conf.html
                         'translations', 'letters.xml', 'numbers.xml', 'station.xml', 'help', 'trainingdata', 'commodities.json'],
           'includes': ['PyQt4.QtNetwork'],
           'excludes': ['PIL', 'setuptools', 'matplotlib', 'wx'],	# random things that tend to get picked up
           'plist': {
               'CFBundleName': 'EliteOCR',
               'CFBundleIdentifier': 'seeebek.eliteOCR',
               'CFBundleShortVersionString': VERSION,
               'CFBundleVersion':  VERSION,
               'LSMinimumSystemVersion': '10.9',
               'NSHumanReadableCopyright': u'© 2014 Sebastian Kaminski',
           }
       }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
